import { NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import { kgNodes } from "@/lib/db/schema";
import { eq, and } from "drizzle-orm";
import { z } from "zod";

export const runtime = "nodejs";

/**
 * PATCH /api/knowledge-bases/[id]/graph/nodes/[nodeId]
 * Update a KG node's description, tags, or dismiss the review flag.
 * Setting needsReview=false marks the node as reviewed/accepted.
 *
 * DELETE /api/knowledge-bases/[id]/graph/nodes/[nodeId]
 * Delete a KG node. Does not affect source chunks.
 */

const patchSchema = z.object({
  description: z.string().min(1).max(2000).optional(),
  tags: z.array(z.string().max(50)).max(10).optional(),
  needsReview: z.literal(false).optional(), // can only dismiss, not set to true via API
});

export async function PATCH(
  req: Request,
  { params }: { params: { id: string; nodeId: string } }
) {
  const session = await auth();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { tenantId } = session.user;

  // Verify node belongs to this tenant's KB
  const node = await db.query.kgNodes.findFirst({
    where: (n, { eq, and }) =>
      and(eq(n.id, params.nodeId), eq(n.kbId, params.id), eq(n.tenantId, tenantId)),
    columns: { id: true },
  });
  if (!node) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const body = await req.json().catch(() => ({}));
  const parsed = patchSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error.issues[0].message }, { status: 400 });
  }

  const updates: Record<string, unknown> = { updatedAt: new Date() };
  if (parsed.data.description !== undefined) updates.description = parsed.data.description;
  if (parsed.data.tags !== undefined) updates.tags = parsed.data.tags;
  if (parsed.data.needsReview === false) {
    updates.needsReview = false;
    updates.reviewReason = null;
    // Mark as manually validated — boost confidence to 1.0
    updates.confidence = 1.0;
    updates.autoGenerated = false;
  }

  const [updated] = await db
    .update(kgNodes)
    .set(updates)
    .where(eq(kgNodes.id, params.nodeId))
    .returning({
      id: kgNodes.id,
      title: kgNodes.title,
      description: kgNodes.description,
      tags: kgNodes.tags,
      needsReview: kgNodes.needsReview,
      confidence: kgNodes.confidence,
      updatedAt: kgNodes.updatedAt,
    });

  return NextResponse.json(updated);
}

export async function DELETE(
  _req: Request,
  { params }: { params: { id: string; nodeId: string } }
) {
  const session = await auth();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { tenantId } = session.user;

  const node = await db.query.kgNodes.findFirst({
    where: (n, { eq, and }) =>
      and(eq(n.id, params.nodeId), eq(n.kbId, params.id), eq(n.tenantId, tenantId)),
    columns: { id: true },
  });
  if (!node) return NextResponse.json({ error: "Not found" }, { status: 404 });

  await db.delete(kgNodes).where(
    and(eq(kgNodes.id, params.nodeId), eq(kgNodes.tenantId, tenantId))
  );

  return new NextResponse(null, { status: 204 });
}
